# Generated by Django 3.1.2 on 2020-10-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201026_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='firm',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=' ', max_length=200)),
                ('quantity', models.IntegerField(max_length=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.service')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_nos', models.CharField(max_length=150)),
                ('entry_time', models.DateTimeField(auto_now=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.firm')),
                ('tax_slab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.taxslab')),
            ],
        ),
    ]
