# Generated by Django 3.1.2 on 2020-10-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201026_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='firm',
            name='mobile_number',
            field=models.CharField(max_length=25),
        ),
    ]
