# Generated by Django 3.1.2 on 2020-10-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201026_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='footer_text',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.invoice'),
        ),
    ]
