# Generated by Django 3.1.2 on 2020-10-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201027_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='footer_text',
            field=models.TextField(blank=True, default=' ', max_length=300),
        ),
    ]
