# Generated by Django 3.1.2 on 2020-10-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20201027_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='entry_time',
            field=models.DateTimeField(),
        ),
    ]
